Mobile Menu
qusai122/Portfolio pull request #16
Opened 2023-03-13 18:34 UTC by qusai122

**In this project:**

- I have added the mobile navbar section
- I have added on click on nav item direct me to the section choosen
- I have added the closing of the navbar

2023-03-13 20:24 UTC, AbayomiOlaoye requested changes
Hi @qusai122 :wave:, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![invalid](https://user-images.githubusercontent.com/99715640/211858554-39090b6b-2f0f-45dd-b5e0-8fb805e56431.gif)

## Invalid Code Review Request

This is supposed to be a pair-programming activity but there is no history of your partner's commit. Kindly ensure both of you contribute to this before submitting another PR :pray: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-14 11:04 UTC, prolajumokeoni requested changes
Hi @qusai122  and @Bellagirl-maker 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed




## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-14 11:04 UTC, prolajumokeoni commented on index.html
> +        </nav>
- [ ] It would be better for the background not to be scrollable when the mobile nav is open, this will create a better user experience  👍🏿 

- Please see the video below ⬇️ 

https://user-images.githubusercontent.com/69638013/224977718-c5151cd6-a127-4ad3-ac2a-f6598f368371.mp4

2023-03-14 11:04 UTC, prolajumokeoni commented on index.html
> +                     <a class="fa-solid fa-bars" id="menu-icon"></a >
Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![Template 1-Mobile-Menu](https://user-images.githubusercontent.com/69638013/224980174-dabf7dd5-4e16-4276-86f3-146eb1271fa6.png) |  ![Screenshot_761](https://user-images.githubusercontent.com/69638013/224980242-17021685-87b0-460d-939a-1a978547d6b5.png)



- [ ] It would be better for the Logo and hamburger not to be visible when the mobile nav is open, adding this functionality will make your design look exactly like the Figma design, great job so far 💪🏿

2023-03-14 13:01 UTC, Olamarx requested changes
#
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has a failed linter.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-14 13:27 UTC, IngDavidTM approved these changes
Hi @qusai122  🙋‍♂️, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

- [OPTIONAL] Please ensure that the "about" button is properly linked to the correct section designated for the "about" page. Currently, the button appears to not be functioning as intended, which may cause confusion and frustration for users attempting to access the relevant information. It is important to rectify this issue in order to improve the overall user experience and ensure that users can easily navigate the website.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-14 13:29 UTC, merged