Finish mobile version 2
qusai122/Portfolio pull request #3
Opened 2023-02-20 13:28 UTC by qusai122

**Finish mobile version of my portfolio :**
 - Perfect my HTML semantics best practices knowledge
 - Perfect my CSS3 layouts using Flexbox to place elements on the page.
 - Perfect my knowledge of GitHub flow
 - Perfect my professional documentation knowledge
 - Was able to understand how to plan my HTML to come up with the desired markup
 - Understand how to parse a Figma design to create a UI.
 - Use Flexbox to place elements on the page.
 - Use CSS Grid to place elements on the page.
 - Build a personal portfolio mobile site.

2023-02-20 15:01 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @qusai122 , |
|Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there! |
| <img src="https://media4.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/> |

## Highlights

- [ ].. ✅ Great design 
- [ ].. ✅ Green linters
- [ ]...✅ Good commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-20 15:01 UTC, joskalenda commented on style.css
> +  align-items: center;
- [x] Hey @qusai122, while you have done a great job till here, I have a few suggestions to raise regarding the project requirement, it is asked to align your card content with `display: grid;` and not flex, please make sure you have the correct setup here.

2023-02-20 15:01 UTC, joskalenda commented on index.html
> +                       <h1 class="card-title">Tonic</h1>
- [x] I don't think you should use an h1 tag in your project again since you already have one on the hero section, based o. the HTML best practice, it is advised to have one h1 title in the app only. I would strongly suggest you update it into an hx one.
- THINK OF DOING THE MODIFICATION ON ALL THE CARD TITLES

2023-02-20 15:01 UTC, joskalenda commented on style.css
> +/** Body elements **/
<img width="762" alt="1" src="https://user-images.githubusercontent.com/77843050/220137503-1389ea4c-46d2-457f-9ef4-3d4a4c07900d.png">

- [x] Please make sure you respect the design properties and design like `padding, margin, font-weight, colors, and font-sizes` as mentioned in the requirement, the text tonic is touching the image above, compared to the original design, it should not look like that.
- [x] As I have highlighted in red circles, please make sure you adjust your spaces around.
- [x] Your button technologies are not well aligned on the left, please fix that too.
- [x] One more thing is the border-radius, think about increasing the pixel a bit to match the Figma design as well

2023-02-20 15:01 UTC, joskalenda commented on style.css
> +  background-color: #fff;
<img width="743" alt="2" src="https://user-images.githubusercontent.com/77843050/220139618-46de3af4-aefd-415d-ab32-aaa5c4c72d7e.png">

- [x] As I said above, please make sure you use the correct colors and font weight for all the text, see? 
- [x] the spaces on the left of the framework section are not the same as the ones on the correct design, please think about how to fix that.
- [x] Take a look closer and catch up on the font weight and color difference between your card texts and the ones o the Figma design, please make sure you arrange that fine too.

2023-02-21 10:10 UTC, qusai122 commented on style.css
> +  align-items: center;
Fixed

2023-02-21 10:10 UTC, qusai122 commented on index.html
> +                       <h1 class="card-title">Tonic</h1>
Fixed

2023-02-21 11:18 UTC, topeogunleye approved these changes
### Hi Team 👋 , 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title :heavy_check_mark:
 
## [Optional] suggestions:
* Nothing to mention.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 11:27 UTC, merged